services:
  # База данных
  db:
    image: postgres:15
    container_name: university_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: university
    volumes:
      # таблицы создаются сами при старте
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
