events {}

http {
    resolver 127.0.0.11 valid=10s ipv6=off;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    add_header 'Access-Control-Allow-Origin' 'http://localhost:8080' always;
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
    add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;
    add_header 'Access-Control-Allow-Credentials' 'true' always;

    server {
        listen 80;

        if ($request_method = 'OPTIONS') {
            return 204;
        }

        location /api/auth {
            set $auth_upstream http://auth-service:8000;
            proxy_pass $auth_upstream;
        }
        location /api/users {
            set $auth_upstream http://auth-service:8000;
            proxy_pass $auth_upstream;
        }
        location /api/schedule {
            set $schedule_upstream http://schedule-service:8000;
            proxy_pass $schedule_upstream;
        }
        location /api/attendance {
            set $attendance_upstream http://attendance-service:8000;
            proxy_pass $attendance_upstream;
        }
        location /api/grades {
            set $grades_upstream http://grades-service:8000;
            proxy_pass $grades_upstream;
        }
        location /api/subjects {
            set $schedule_upstream http://schedule-service:8000;
            proxy_pass $schedule_upstream;
        }
        location /api/rooms {
            set $schedule_upstream http://schedule-service:8000;
            proxy_pass $schedule_upstream;
        }

        location / {
            set $frontend_upstream http://frontend:80;
            proxy_pass $frontend_upstream;
            proxy_redirect off;
        }
    }
}
